"""initial schema baseline

Revision ID: cd311deb862b
Revises: 
Create Date: 2026-07-21 20:07:37.474666
"""
from alembic import op
import sqlalchemy as sa


revision = 'cd311deb862b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('area_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bereich', sa.String(length=60), nullable=False),
    sa.Column('buero_erlaubt', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('area_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_permissions_bereich'), ['bereich'], unique=True)

    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art', sa.Enum('direkt', 'gruppe', name='threadart'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kennzeichen', sa.String(length=20), nullable=False),
    sa.Column('hersteller', sa.String(length=60), nullable=False),
    sa.Column('modell', sa.String(length=80), nullable=False),
    sa.Column('fin', sa.String(length=40), nullable=True),
    sa.Column('erstzulassung', sa.Date(), nullable=True),
    sa.Column('km_stand', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('einsatzbereit', 'unterwegs', 'werkstatt_geplant', 'in_reparatur', 'eingeschraenkt', 'ausgefallen', name='vehiclestatus'), nullable=False),
    sa.Column('typ', sa.Enum('pkw', 'sprinter', 'lkw', 'haenger', name='vehicletyp'), nullable=False),
    sa.Column('untertyp', sa.String(length=80), nullable=True),
    sa.Column('zugfahrzeug_id', sa.Integer(), nullable=True),
    sa.Column('leasing_anbieter', sa.String(length=120), nullable=True),
    sa.Column('leasing_ende', sa.Date(), nullable=True),
    sa.Column('monatliche_fixkosten', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hu_faellig', sa.Date(), nullable=True),
    sa.Column('sp_faellig', sa.Date(), nullable=True),
    sa.Column('uvv_faellig', sa.Date(), nullable=True),
    sa.Column('tacho_faellig', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('geloescht_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zugfahrzeug_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_kennzeichen'), ['kennzeichen'], unique=False)

    op.create_table('fuel_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kartennummer', sa.String(length=40), nullable=False),
    sa.Column('anbieter', sa.String(length=80), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_cards_kartennummer'), ['kartennummer'], unique=True)

    op.create_table('safety_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=120), nullable=False),
    sa.Column('ablauf_am', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'geschaeftsfuehrung', 'buero', 'it', 'fahrer', name='role'), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('aktiv', 'abwesend', 'inaktiv', name='userstatus'), nullable=False),
    sa.Column('geburtstag', sa.Date(), nullable=True),
    sa.Column('nur_notfall_anrufen', sa.Boolean(), nullable=False),
    sa.Column('erreichbarkeit', sa.Enum('gruen', 'rot', 'zeitplan', name='erreichbarkeit'), nullable=False),
    sa.Column('erreichbar_von', sa.Time(), nullable=True),
    sa.Column('erreichbar_bis', sa.Time(), nullable=True),
    sa.Column('foto_pfad', sa.String(length=400), nullable=True),
    sa.Column('urlaubstage_kontingent', sa.Integer(), nullable=False),
    sa.Column('fahrerkarte_ablauf', sa.Date(), nullable=True),
    sa.Column('adr_karte_ablauf', sa.Date(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('geloescht_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('damage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('prioritaet', sa.Enum('info', 'normal', 'kritisch', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('gemeldet', 'uebernommen', 'in_reparatur', 'erledigt', name='damagestatus'), nullable=False),
    sa.Column('nachricht_an_gf', sa.Text(), nullable=True),
    sa.Column('schadensdatum', sa.Date(), nullable=True),
    sa.Column('ort', sa.String(length=200), nullable=True),
    sa.Column('position_x', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('position_y', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('von', sa.Date(), nullable=False),
    sa.Column('bis', sa.Date(), nullable=False),
    sa.Column('notiz', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('offen', 'genehmigt', 'abgelehnt', name='leavestatus'), nullable=False),
    sa.Column('entschieden_von_id', sa.Integer(), nullable=True),
    sa.Column('entschieden_am', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entschieden_von_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ersteller_id', sa.Integer(), nullable=False),
    sa.Column('mitarbeiter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ersteller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('art', sa.Enum('urlaub', 'krank', 'stunden', name='entryart'), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('bis', sa.Date(), nullable=True),
    sa.Column('stunden', sa.Float(), nullable=True),
    sa.Column('notiz', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frage', sa.String(length=255), nullable=False),
    sa.Column('erstellt_von_id', sa.Integer(), nullable=False),
    sa.Column('offen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['erstellt_von_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('faellig_am', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('offen', 'erledigt', name='taskstatus'), nullable=False),
    sa.Column('zugewiesen_user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_von_id', sa.Integer(), nullable=False),
    sa.Column('erledigt_am', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['erstellt_von_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['zugewiesen_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('damage_id', sa.Integer(), nullable=True),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('quelle', sa.Enum('schaden', 'pruefung', 'wartung', 'werkstatt', 'leasing', 'versicherung', 'allgemein', name='appointmentsource'), nullable=False),
    sa.Column('faellig_am', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('offen', 'erledigt', name='appointmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['damage_id'], ['damage_reports.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('damage_id', sa.Integer(), nullable=True),
    sa.Column('mitarbeiter_id', sa.Integer(), nullable=True),
    sa.Column('kategorie', sa.Enum('leasing', 'finanzierung', 'reparatur', 'wartung', 'reifen', 'versicherung', 'steuer', 'kraftstoff', 'adblue', 'tankkarte', 'maut', 'pruefung', 'werkstatt', 'ausruestung', 'sonderzahlung', 'sonstiges', name='costcategory'), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('beschreibung', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['damage_id'], ['damage_reports.id'], ),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pfad', sa.String(length=400), nullable=False),
    sa.Column('typ', sa.String(length=60), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['damage_id'], ['damage_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_antworten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('antwort', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_user')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('geloescht', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('produkt', sa.String(length=60), nullable=False),
    sa.Column('menge_liter', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['fuel_cards.id'], ),
    sa.ForeignKeyConstraint(['cost_id'], ['cost_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'datum', 'betrag', 'produkt', name='uq_fuel_tx')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('absender', sa.String(length=200), nullable=False),
    sa.Column('betreff', sa.String(length=300), nullable=False),
    sa.Column('rechnungsnummer', sa.String(length=80), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rechnungsdatum', sa.Date(), nullable=True),
    sa.Column('eingegangen_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('anhang_pfad', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Enum('eingegangen', 'geprueft', 'ungeklaert', name='invoicestatus'), nullable=False),
    sa.Column('vorschlag_kategorie', sa.Enum('leasing', 'finanzierung', 'reparatur', 'wartung', 'reifen', 'versicherung', 'steuer', 'kraftstoff', 'adblue', 'tankkarte', 'maut', 'pruefung', 'werkstatt', 'ausruestung', 'sonderzahlung', 'sonstiges', name='costcategory'), nullable=True),
    sa.Column('vorschlag_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('ist_duplikat', sa.Boolean(), nullable=False),
    sa.Column('hinweis', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('kategorie', sa.Enum('leasing', 'finanzierung', 'reparatur', 'wartung', 'reifen', 'versicherung', 'steuer', 'kraftstoff', 'adblue', 'tankkarte', 'maut', 'pruefung', 'werkstatt', 'ausruestung', 'sonderzahlung', 'sonstiges', name='costcategory'), nullable=True),
    sa.Column('cost_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cost_id'], ['cost_entries.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['vorschlag_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('foto_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foto_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_memberships')
    op.drop_table('parking_spots')
    op.drop_table('invoices')
    op.drop_table('fuel_transactions')
    op.drop_table('chat_messages')
    op.drop_table('poll_antworten')
    op.drop_table('documents')
    op.drop_table('cost_entries')
    op.drop_table('appointments')
    op.drop_table('tasks')
    op.drop_table('polls')
    op.drop_table('personnel_entries')
    op.drop_table('notes')
    op.drop_table('leave_requests')
    op.drop_table('damage_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('safety_items')
    with op.batch_alter_table('fuel_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_cards_kartennummer'))

    op.drop_table('fuel_cards')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_kennzeichen'))

    op.drop_table('vehicles')
    op.drop_table('chat_threads')
    with op.batch_alter_table('area_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_permissions_bereich'))

    op.drop_table('area_permissions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
