"""add passwort_aendern_erforderlich

Revision ID: e5f87bcc7275
Revises: f021c2c5d64e
Create Date: 2026-07-24 22:35:51.355606
"""
from alembic import op
import sqlalchemy as sa


revision = 'e5f87bcc7275'
down_revision = 'f021c2c5d64e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwort_aendern_erforderlich', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('passwort_aendern_erforderlich')

    # ### end Alembic commands ###
