"""add receipts table

Revision ID: f021c2c5d64e
Revises: cd311deb862b
Create Date: 2026-07-21 20:15:54.144561
"""
from alembic import op
import sqlalchemy as sa


revision = 'f021c2c5d64e'
down_revision = 'cd311deb862b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfad', sa.String(length=400), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=True),
    sa.Column('notiz', sa.String(length=255), nullable=True),
    sa.Column('hochgeladen_von_id', sa.Integer(), nullable=False),
    sa.Column('abgeholt', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hochgeladen_von_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    # ### end Alembic commands ###
